on:
  push:
    branches:
      - main
  pull_request:

name: ci
jobs:
  tests:
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: corepack enable && corepack prepare
      # Note: actions/setup-node doesn't yet provide parameters for corepack, we need to run it again after enabling it
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install
      - run: npm test
        env:
          MOCHA_THROW_DEPRECATION: false
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install
      - run: npm run lint
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install
      - run: npm run docs
      - uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: docs/
